name: Cron Update Traffic Database

on:
  schedule:
    - cron: '0 8 * * *'  # 8:30 UTC = 1:30 AM Arizona time
  workflow_dispatch:

jobs:
  fetch_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Call /cron/fetch-all endpoint
        run: |
          curl -X 'PUT' \
            'https://github-traffic-api.onrender.com/cron/update-db' \
            -H 'accept: application/json' \
            -H 'github-traffic-api-key: ${{ secrets.PROJECT_KEY }}' \
            -d ''