name: Fetch GitHub Traffic and Commit DB

on:
  schedule:
    - cron: '30 8 * * *'  # 8:30 UTC = 1:30 AM Arizona time
  workflow_dispatch:

jobs:
  fetch_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout traffic-db-storage branch
        uses: actions/checkout@v4
        with:
          ref: traffic-db-storage

      - name: Set up Git config
        run: |
          git config user.name "Shawn N"
          git config user.email "79764274+ShawnN24@users.noreply.github.com"

      - name: Commit updated DB file
        run: |
          git add traffic.db
          git commit -m "Update traffic.db on schedule" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:traffic-db-storage