name: Trigger API Cron Job

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call /cron/fetch-all endpoint
        run: |
          curl -X 'POST' \
            'https://github-traffic-api.onrender.com/cron/fetch-all' \
            -H 'accept: application/json' \
            -H 'github-traffic-api-key: ${{ secrets.PROJECT_KEY }}' \
            -d ''